### ISSUE TITLE
Muse codes and pre-trained model

### ISSUE THREAD

**Issue by nightlight9013** [ggjy/DeLVM#7]
Hi, thanks for the great work.

The paper claims that you use an off-the-shelf VQGAN from Muse.

Could you kindly share which specific Muse code and pretrained model you used for this project?

 Additionally, it would be really helpful to know where these resources can be found.
 
Thanks again!

**Comment by ggjy** [comment]
You can find the corresponding ckpt [here](https://github.com/ggjy/DeLVM/releases/tag/vqgan-f16-8192).
